spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/jmolecules-examples?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: rootp@assword
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

springdoc:
  swagger-ui:
    path: /swagger-ui.html